### ISSUE TITLE
Question: bash 4.1 vs 4.2 as minimum requirement

### ISSUE THREAD

**Issue by MrAnno** [Anvil/bash-argsparse#12]
Hi,

The `master` branch has a patch that started using `[[ -v ]]`, which is a bash 4.2 feature:
https://github.com/Anvil/bash-argsparse/commit/0b2bbf641f5a361c684dcaf61a1c36eaf364bcae

https://github.com/bminor/bash/blob/master/CHANGES#L3642

README states that `GNU bash version >= 4.1` is required.

Do you have plans to bump the min. required bash version to 4.2? Or alternatively, can I open a pull request that replaces `-v` with something that is 4.1-compatible?

**Comment by Anvil** [comment]
Yeah, you're right, it's wrong :)

Bash 4.1 is 10 years old, I think it's time to move on to 4.2. I very often use [[ -v ]] nowadays.

**Comment by MrAnno** [comment]
I've opened a pull request about the version bump (#13).

This is a really cool library, thank you for open-sourcing it :)
