### ISSUE TITLE
Link to doc is broken

### ISSUE THREAD

**Issue by R-Le-Gall** [Anvil/bash-argsparse#6]
It's totaly minor but the link to your doxygen documentation is broken, there's only a 1.6.1 version on http://argsparse.livna.org

**Comment by Anvil** [comment]
Sorry about that. :) It's fixed

**Comment by MaxenceAdnot** [comment]
http://argsparse.livna.org is broken again

**Comment by Anvil** [comment]
Fixed again. :p

**Comment by MaxenceAdnot** [comment]
Thank you so much sir !
