### ISSUE TITLE
Accepted values not working

### ISSUE THREAD

**Issue by Croissong** [Anvil/bash-argsparse#7]
Hi,
the [acceptable values feature](https://github.com/Anvil/bash-argsparse/blob/master/tutorial/7-value-checking#L16) does not work for me.
I am using `GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)`.
The [__argsparse_is_array_declared check](https://github.com/Anvil/bash-argsparse/blob/master/argsparse.sh#L828) never returns true.
Replacing the line with a simple is-set check `[[ ! -z ${!array_name+x}  ]]` ([stackoverflow](https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash)) however, works for me. 
I could create an PR, if you want :) 

Thanks

**Comment by Anvil** [comment]
Hi, thank you for the report, I can reproduce that on my bash 4.4.23 setup on fedora 28. There's a change in the `declare -p` output for arrays in bash 4.4.

See latest commit on master. That should do the trick.

**Comment by Croissong** [comment]
Thanks so much, awesome work!
