### ISSUE TITLE
Use bash-argsparse inside functions directly

### ISSUE THREAD

**Issue by moocan** [Anvil/bash-argsparse#8]
Hello,

First thanks for this great arguments parsing tool.

I'm trying to use it inside function directly as I need to control function usage.
Some exit statement as in usage() function end all
I tried to use a return 1 statement but I have some error because parsing seems to continue and do not stop anymore after using -h argument.

I have errors as : 
> -bash: --source-path: option is mandatory.
> -bash: --destination-path: option is mandatory.

Is there any way to use your bash-argsparse inside functions ?

Thanks in advance for your advices.

Kind regards

**Comment by Anvil** [comment]
I'm sorry, but right now this is not possible and honestly I do not intend to fix that (though I would accept a patch). It seems a bit overkill to me, but if you have big script-sized functions this might prove useful.

As you have pointed out, there is the `exit` statement in the usage function. It's suppose to act like an exception and abort execution.

Also, there are plenty of side effects induced by the declaration of options and the inner stuff of the library itself. All the global variables (the top level `declare` statements in the library) are meant to be altered by the different functions.

The only way you could actually do that right now would be if:
1. You never nest argparse setups (or do that on purpose, like inheritance for classes) _and_
2. You must declare your functions as subshells:
```bash
my_function() (
    # Notice the parenthesis instead of curly brackets.
    argsparse_use_option =blah: "option blah"
    argsparse_parse_options "$@"
)
```

The setback is that your functions will never be able to have any side effects on the caller.

**Comment by Anvil** [comment]
Does it work for you ? Can i close this issue ?
